version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: interseguros
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgsql
    ports:
      - "5432:5432"
    networks:
      - app-network

  Interseguros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conaseguradoras
    ports:
      - "8080:8080"
    networks:
      - app-network
    image: imaaseguradoras
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/interseguros
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pgsql
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

